---
title: "Corona Virus Report"
author:
- familyname: Bharadwaj
  othernames: Mayunk
  address: Monash Universtidy
  email: mbha0014@student.monash.edu
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```



\section*{Country XX1 and YY1"}

```{r data-read-in}
dat <- read_csv("Data/worldwidecases.csv")

dat_swe_nzl <- dat %>%
  filter(countryterritoryCode %in% c("NZL","SWE"))
```


```{r swe-table, fig.cap="Coronavirus Deaths by Month in Sweden}
swe_table <- dat_swe_nzl %>%
  filter(countryterritoryCode == "SWE") %>%
  group_by(month) %>%
  count() %>%
  kable()
```

The above data in Table \@ref(tab:swe-table)) shows monthly death counts in Sweden

```{r nz-bar, fig.cap="Coronavirus Deaths by Month in New Zealand"}
nz_graph <- dat_swe_nzl %>%
  filter(countryterritoryCode == "SWE") %>%
  group_by(month) %>%
  count()

nz_graph %>%
  ggplot(aes(x=month)) +
  geom_bar()
```

The above Figure \@ref(fig:nz-bar) displays coronavirus deaths by Month in New Zealand/

Junk paper reference @BC64

\section*{Country XX2 and YY2}

\section*{Country XX3 and YY3}



